baseURL: https://example.org/
languageCode: en-us
title: My New Hugo Site
theme: coder
enableRobotsTXT: true

params:
  author: "Your Name"
  info: "Info about yourself"
  description: "Description of your site"
  keywords: "blog,developer,personal"
  gravatar: "your@example.com"

  faviconSVG: "/img/favicon.svg"
  favicon_32: "/img/favicon-32x32.png"
  favicon_16: "/img/favicon-16x16.png"

  since: 2020

  enableTwemoji: true

  colorScheme: "auto"
  hidecolorschemetoggle: false

  social:
    - name: "Github"
      icon: "fa-brands fa-github fa-2x"
      weight: 1
      url: "https://github.com/<github-username>"
    - name: "LinkedIn"
      icon: "fa-brands fa-linkedin fa-2x"
      weight: 1
      url: "https://www.linkedin.com/in/<linkedin-username>/"

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"
  author: "authors"

menu:
  main:
    - name: "About"
      weight: 1
      url: "about/"
